#ifndef COMMA
#define COMMA ,
#endif
X(Q, "Q") COMMA 
X(OPEN_PAREN, "(") COMMA 
X(CLOSE_PAREN, ")") COMMA 
X(OPEN_BRACKET, "[") COMMA
X(CLOSE_BRACKET, "]") COMMA
X(OPEN_ANGLE_BRACKET, "<") COMMA
X(CLOSE_ANGLE_BRACKET, ">") COMMA
X(OPEN_BRACE, "{") COMMA
X(CLOSE_BRACE, "}") COMMA
X(OPEN, "OPEN") COMMA
X(CLOSE, "CLOSE") COMMA
X(START, "START") COMMA
X(END, "END") COMMA
X(CODE, "CODE") COMMA
X(TEMPLATE, "TEMPLATE")
#undef X
#undef COMMA
